# Make the prefix Ctrl+a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Make things more vim-like
# {
setw -g mode-keys vi


# Use vim keys for moving panes.
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Similarly for resizing panes.
bind < resize-pane -L 10
bind > resize-pane -R 10
bind - resize-pane -D 10
bind + resize-pane -U 10

# use <prefix> s for horizontal split
bind s split-window -v
# use <prefix> v for vertical split
bind v split-window -h
# }

set -g mouse on

# Support things like ctrl+arrow keys
set-window-option -g xterm-keys on

# ¯\_(ツ)_/¯
set -sg escape-time 15
set -g default-terminal "screen-256color"
set-option -sg terminal-overrides ',xterm-256color:RGB'
set-option -g focus-events on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'erikw/tmux-powerline'

# run this:
# brew install --cask font-monaspace-nerd-font font-noto-sans-symbols-2
# brew install bash bc coreutils gawk gh glab gsed jq nowplaying-cli
set -g @plugin 'catppuccin/tmux#v2.1.2'

# Theme config
set -g @catppuccin_window_status_style "rounded"

run ~/.config/tmux/plugins/tmux/catppuccin.tmux
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_date_time}"

set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_text " #W "

# MacOS opts
if-shell "uname | grep -q Darwin" {
  bind -n C-y run "tmux show-buffer | pbcopy"
}

# WSL opts
if-shell "cat /proc/version | grep -q microsoft" {
  bind -n C-y run "tmux save-buffer - | clip.exe"
}

run '~/.tmux/plugins/tpm/tpm'
