[window]
opacity = 0.7
blur = true
option_as_alt = "Both"

[font]
size = 12

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]
